# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

services:
  - postgresql

before install:
  - psql - c 'create database tracker;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -r.yakimkin@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="c498ffeb-3867-4805-845a-8dc8f67d64f0"